server:
  port: 18902
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/panda?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: /mapper/**/**.xml